# Generated by Django 4.1.10 on 2023-10-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_lesson_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
