# Generated by Django 4.1.10 on 2023-10-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_userquizresult_question_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userquizresult',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='userquizresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='UserQuizResult',
        ),
    ]
