# Generated by Django 4.2.6 on 2023-10-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_quiz_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
