# Generated by Django 4.2.6 on 2023-10-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_remove_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='lesson_images/'),
        ),
    ]
