# Generated by Django 4.2.6 on 2023-10-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_course_image_lesson_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
    ]
