# Generated by Django 4.2.6 on 2023-10-11 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_remove_course_image_remove_lesson_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('choice_1', models.CharField(default='', max_length=255)),
                ('choice_2', models.CharField(default='', max_length=255)),
                ('choice_3', models.CharField(default='', max_length=255)),
                ('choice_4', models.CharField(default='', max_length=255)),
                ('correct_choice', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.test')),
            ],
        ),
    ]
