# Generated by Django 4.2.6 on 2023-10-11 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_test_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='lesson',
        ),
        migrations.AddField(
            model_name='test',
            name='Lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.lesson'),
        ),
    ]
